### PR TITLE
Fix bug where fields preceding `ExpandableAttribute` were not modifiable (#294)

### LINKED ISSUE #294: [Bug][Expandable] Will make other expandable element which in front of this Attirbute not update
Here's the code that reproduce the bug:
```C#
    public class ExpandableTest : MonoBehaviour
    {
        public UnityEvent onClick;//Bug: the List can't be modify
        [ResizableTextArea]
        public string multiLine;//Bug: the content can't be save after hit 'Enter'
        [Expandable]
        public ScriptableObject obj0;
    }

```

When you edit the onClick/multiLine field in Inspector, you will find that their value will not get save:
image

But if you move the obj0 on top of the onClick/multiLine field, they will work again.

Unity Version: 2021.2.7f1c1

### PR DESCRIPTION
**Pull request by rhys-vdw**
Please refer to #294 for my investigation notes and uncertainties around intent of removed line.

Closes #294

### CODE REVIEW

**Comment by dbrizov** [comment]
Great, I will test it and merge it in the weekend :)

**Comment by rhys-vdw** [comment]
The thing I was most confused by was that this line wasn't added in the commit that introduced the bug. So it's a bit of programming by permutation. You might want to use your brilliant unity editor brain to have a think about whether it's actually treating the cause and not a symptom.

**Comment by rhys-vdw** [comment]
@dbrizov I'm sure you're a busy man, so I hope you don't mind a nudge on this one. 🙏

**Comment by dbrizov** [comment]
> @dbrizov I'm sure you're a busy man, so I hope you don't mind a nudge on this one. 🙏

@rhys-vdw I know, sorry. I honestly completely forgot to merge it. I started tutoring students, apart from my job, and I barely have any free time. I will try to do my best and merge it as soon as possible. It should be a quick merge anyway :)

**Comment by dbrizov** [comment]
Merged in **v2** 7cddf69bca9d09eb8205498ebaf6bdc50f7641fd

**Comment by rhys-vdw** [comment]
Thanks mate!

**Comment by dbrizov** [comment]
I thank you. And, yeah sorry for keeping you waiting, thanks for the patience

**Pull request closed without merging**
