### PR TITLE
Exclude test assembly from builds (#287)

### LINKED ISSUE #287: [Improvement] Unnecessary DLL in Build output
I'm using this library via openupm in my game and am quite happy with being able to do that.
There is however one thing that bugs me a little:
I can't prevent the **NaughtyAttributes.Test.dll** from landing in the build output of my game even though I'm never using any of it. It's only required for the Samples which I am not using.

I briefly tried to fix this using either checkboxes within the "NaughtyAttributes.Test"-AssemblyDefinition or moving the sources to the sample folder. I didn't manage to solve it doing that and that's why I decided to open this Issue instead of just creating a PR.

### PR DESCRIPTION
**Pull request by rhys-vdw**
Do not include the test assembly in builds.

Solution:
- Move assembly into Samples folder so that it can be selectively imported as required for the sample scene and assets. https://docs.unity3d.com/Manual/cus-samples.html)
- Prevent automatic import of Samples folder by suffixing it with `~` (https://docs.unity3d.com/Manual/SpecialFolders.html)
- Add a symlink from `Assets/Samples` to the existing `Samples~` folder so that it is visible and editable while working in _this repository_ (as the regular folder is hidden from Unity always).

Closes #287

### CODE REVIEW

**Comment by rhys-vdw** [comment]
Ah crap, seems I had autocrlf enabled and it's modified all the line endings. I'll try to clean it up.

**Comment by rhys-vdw** [comment]
Ugh, this is annoying. I fixed the line ending changes but it seems that symlinks are not well supported in Windows. Not sure if this will work after all.

**Comment by rhys-vdw** [comment]
This approach was bad. I might try this again and see if I can get something that you find appropriate.

**Comment by dbrizov** [comment]
Check #291
I haven't tested it yet, but it might help get rid of all assemblies, not only the test assembly.

**Comment by rhys-vdw** [comment]
I'm quite sure this is the recommended way of handling this: https://github.com/dbrizov/NaughtyAttributes/issues/287#issuecomment-1031217771

**Pull request closed without merging**
