### PR TITLE
Fix Dropdown null errors before first serialize (#256)

### LINKED ISSUE #256: Dropdown null errors on first time added
When adding a component that has a dropdown of a nullable type (tested with strings) - there are null errors until the first successful serialization (with the default value)

Fixed this in a fork, will submit a PR soon

### PR DESCRIPTION
**Pull request by JonLevin25**
fixes #256

### CODE REVIEW

**Comment by JonLevin25** [comment]
@dbrizov Can merge? it's just a null check

**Comment by dbrizov** [comment]
Sorry for the late reply, I am pretty busy these days. I am planning to make a big update in the weekend. I have a lot of pull requests and issues to fix.

**Comment by JonLevin25** [comment]
np, I appreciate the reply and looking forward to the update 👍

**Review by ahnafnafee — COMMENTED** [review]
This still raises error on my end. What did fix for me was checking if the length of values was greater than 0.
```
if (values.Length > 0)
{
	object newValue = values[newIndex];
	
	if (!dropdownField.GetValue(target).Equals(newValue))
	{
```

**Comment by dbrizov** [comment]
Merge in 08efcae01bef12dd3f1740de6066f72718525ae5

**Pull request closed without merging**
